replicaCount: 1

image:
  repository: janekbaraniewski/octoprint
  tag: latest
  pullPolicy: IfNotPresent

printer:
  enabled: false
  port: 3333

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts: []
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
