replicaCount: 1

image:
  repository: janekbaraniewski/octoprint
  tag: 1.3.10
  pullPolicy: IfNotPresent

printer:
  enabled: true
  port: 3333

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations: {}
  paths: []
  hosts: ["ender3v2.otakuneko.net"]
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
